### ISSUE TITLE
Proaktivität integrieren

### ISSUE THREAD

**Issue by fabiankuffer** [pda-aswe/casewelcome#6]
Die vordefinierte Proaktivität integrieren.

**Comment by TobiasLukasewitz** [comment]
Use Case liest Ausgabezeitpunkt aus der Präferenz und prüft ob der Zeitpunkt erreicht wurde. Ist er das wird die Nachricht zusammengebaut und ausgegeben. Der Tag der letzten Ausführung wird sich gemerkt um eine erneute Ausführung zu verhindern
